title: "Na, Naa Na Na Na, Na Naa Naa Naa Na"

description: "Visulzing Katamari Damacy gameplay input."

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude: [
    "node_modules",
    "process",
    "server",
    "src"
]